### ISSUE TITLE
Possible Path Issue on Windows

### ISSUE THREAD

**Issue by seep** [fabriziomoscon/rootpath#1]
Hey, had some trouble running this on Windows, and I think it has to do with the colon character on https://github.com/fabriziomoscon/rootpath/blob/master/pathSetup.js#L16. My `require` calls weren't resolving, and after changing the colon to `path.delimiter` it worked. I couldn't find any documentation on using a colon in a path; do you have a link for that? What is the colon supposed to indicate in the path?

**Comment by sandfox** [comment]
We didn't have in windows in mind we wrote this so there aren't any cross platform compatibility bits in it. If you can put together a quick PR I'll test it on Linux/OSX and merge it.

**Comment by sandfox** [comment]
The colon is a separator between multiple definitions of path (kinda like the comma in CSV)

**Comment by sandfox** [comment]
thanks for the PR, thats all merged in but unfortunately I don't have publish rights for this module on npm and @fabriziomoscon is away till the 27th so it will be a few days before this gets in npm

**Comment by seep** [comment]
Thanks for the quick merge, no problem about NPM. I can just reference the repo for the time being.

**Comment by fabriziomoscon** [comment]
version 0.1.2 is on npm now
