### ISSUE TITLE
`path.resolve()`

### ISSUE THREAD

**Issue by tobius** [fabriziomoscon/rootpath#6]
What use-cases does this module solve that simply using `path.resolve()` does not?

**Comment by tobius** [comment]
Nm, I've been working around ES module import changes for a while now (e.g. spec refuses to support `NODE_PATH`) and forgot why I had to quit using `rootpath`. I enjoyed using this module on many of my past projects, thank you for creating and sharing it.

**Comment by missinglink** [comment]
Hi @tobius, this module was written in 2013, back when we were running node v0.6 😱
A lot has changed since then, so this module might not be required by modern applications.

Glad you enjoyed it.
